name: blood_distirbution
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  cloud_firestore: 3.1.10
  cupertino_icons: ^1.0.2
  dropdown_search: 2.0.1
  firebase_auth: 3.3.10
  firebase_core: 1.13.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: 0.9.2
  geocoding: 2.0.4
  geolocator: 8.2.0
  get: 4.6.1
  google_fonts: 2.3.1
  location: ^4.3.0
  maps_launcher: ^2.0.1
  url_launcher: 6.0.20

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
