name: blood_distirbution
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  firebase_core: 1.13.1
  cloud_firestore: 3.1.10
  google_fonts: 2.3.1
  dropdown_search: 2.0.1
  firebase_auth: 3.3.10
  geolocator: 8.2.0
  flutter_phone_direct_caller: 2.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

